const CACHE = 'forma-c90ca672';
const FILES = ["./", "index.html", "manifest.webmanifest", "ex/ab-roller.webp", "ex/barbell-bench-press-medium-grip.webp", "ex/barbell-curl.webp", "ex/barbell-deadlift.webp", "ex/barbell-glute-bridge.webp", "ex/barbell-hip-thrust.webp", "ex/barbell-incline-bench-press-medium-grip.webp", "ex/barbell-shrug.webp", "ex/barbell-squat.webp", "ex/bent-over-barbell-row.webp", "ex/bicycling-stationary.webp", "ex/butterfly.webp", "ex/cable-crossover.webp", "ex/cable-crunch.webp", "ex/cable-rope-overhead-triceps-extension.webp", "ex/calf-press-on-the-leg-press-machine.webp", "ex/close-grip-barbell-bench-press.webp", "ex/concentration-curls.webp", "ex/crunches.webp", "ex/dips-chest-version.webp", "ex/dips-triceps-version.webp", "ex/dumbbell-bench-press.webp", "ex/dumbbell-bicep-curl.webp", "ex/dumbbell-flyes.webp", "ex/dumbbell-lunges.webp", "ex/dumbbell-shoulder-press.webp", "ex/elliptical-trainer.webp", "ex/ez-bar-skullcrusher.webp", "ex/face-pull.webp", "ex/farmer-s-walk.webp", "ex/front-dumbbell-raise.webp", "ex/hack-squat.webp", "ex/hammer-curls.webp", "ex/hanging-leg-raise.webp", "ex/hyperextensions-back-extensions.webp", "ex/incline-dumbbell-press.webp", "ex/leg-extensions.webp", "ex/leg-press.webp", "ex/leverage-chest-press.webp", "ex/lying-leg-curls.webp", "ex/one-arm-dumbbell-row.webp", "ex/one-legged-cable-kickback.webp", "ex/palms-down-wrist-curl-over-a-bench.webp", "ex/palms-up-barbell-wrist-curl-over-a-bench.webp", "ex/plank.webp", "ex/preacher-curl.webp", "ex/pullups.webp", "ex/pushups.webp", "ex/romanian-deadlift.webp", "ex/rope-jumping.webp", "ex/rowing-stationary.webp", "ex/running-treadmill.webp", "ex/russian-twist.webp", "ex/seated-bent-over-rear-delt-raise.webp", "ex/seated-cable-rows.webp", "ex/seated-calf-raise.webp", "ex/side-lateral-raise.webp", "ex/split-squat-with-dumbbells.webp", "ex/stairmaster.webp", "ex/standing-calf-raises.webp", "ex/standing-military-press.webp", "ex/sumo-deadlift.webp", "ex/t-bar-row-with-handle.webp", "ex/thigh-abductor.webp", "ex/triceps-pushdown-rope-attachment.webp", "ex/triceps-pushdown.webp", "ex/upright-barbell-row.webp", "ex/wide-grip-lat-pulldown.webp", "fonts/manrope-cyrillic-400-normal.woff2", "fonts/manrope-cyrillic-500-normal.woff2", "fonts/manrope-cyrillic-600-normal.woff2", "fonts/manrope-cyrillic-700-normal.woff2", "fonts/manrope-cyrillic-800-normal.woff2", "fonts/manrope-latin-400-normal.woff2", "fonts/manrope-latin-500-normal.woff2", "fonts/manrope-latin-600-normal.woff2", "fonts/manrope-latin-700-normal.woff2", "fonts/manrope-latin-800-normal.woff2", "fonts/unbounded-cyrillic-500-normal.woff2", "fonts/unbounded-cyrillic-700-normal.woff2", "fonts/unbounded-latin-500-normal.woff2", "fonts/unbounded-latin-700-normal.woff2", "icons/icon-180.png", "icons/icon-192.png", "icons/icon-512.png", "icons/maskable-512.png"];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k!==CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url); if (url.origin !== location.origin) return;
  if (e.request.mode === 'navigate'){ e.respondWith(fetch(e.request, {cache:'no-cache'}).then(r => { const c = r.clone(); caches.open(CACHE).then(x => x.put('index.html', c)); return r; }).catch(() => caches.match('index.html'))); return; }
  e.respondWith(caches.match(e.request).then(r => r || fetch(e.request).then(res => { const c = res.clone(); caches.open(CACHE).then(x => x.put(e.request, c)); return res; })));
});
